### ISSUE TITLE
node-sass issue

### ISSUE THREAD

**Issue by vaibhavpacharya** [ShankarSumanth/Angular2-RecordRTC#5]
Hi Shankar,
After running yarn on my windows 10 machine, it fails to compile the node-sass package.

```
Building: C:\Program Files\nodejs\node.exe C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Vaibhav Acharya\\Desktop\\Web Devlopment Bootcamp\\Angular_2\\Angular2-RecordRTC-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@8.1.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Vaibhav Acharya\\Desktop\\Web Devlopment Bootcamp\\Angular_2\\Angular2-RecordRTC-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Vaibhav Acharya\Desktop\Web Devlopment Bootcamp\Angular_2\Angular2-RecordRTC-master\node_modules\node-sass
gyp ERR! node -v v8.1.2
```
I tried manually updating the node-sass package, but instead it started giving new 200+ errors regarding material design. Please help.

**Comment by ShankarSumanth** [comment]
Hi @vaibhavpacharya ,

I tried to clone my repo and seems to be working fine.

Can you try to update your node, npm and yarn to latest version and try it? Also try to clean your npm cache (with force flag) and re download all dependencies
This is my current configuration
```
yarn: 1.3.2
node:9.3.0
npm: 5.6.0
```

Let me know if it helps. Also see this issue might be related https://github.com/sass/node-sass/issues/1176

**Comment by vaibhavpacharya** [comment]
Hi @ShankarSumanth ,
It was a problem with gulp-sass and node-sass. 
I resolved the issue by following instructions from this => https://github.com/jakearchibald/wittr/issues/20
Thank You.

**Comment by vibingopal** [comment]
Hi Vaibhav,
are you able to record the application from your end ? instead of the people presenting the demo.

**Comment by vaibhavpacharya** [comment]
@vibingopal  Yes, I am.

**Comment by vibingopal** [comment]
Could you please let me know how you are recording the application. When iam following the example, iam able to record the person who is presenting not on the application. I want to record the flow of application through browser

**Comment by vibingopal** [comment]
Hi Vaibhav, 

Can you please let me know or you have any example to share with ? 

Thanks

**Comment by vibingopal** [comment]
Hello Vaibhav,

Will you let you know how you are playing your recorded video. After i recorded, my video is not getting played in webm format. I appreciate if you do reply.
